### ISSUE TITLE
attr_reader/writer/accessor

### ISSUE THREAD

**Issue by connorshea** [AaronC81/parlour#3]
I'd like a way to generate `attr_reader`, `attr_writer`, and `attr_accessor`s in the RBIs generated by Parlour :)

Probably with `create_attr_reader`, `create_attr_writer`, and `create_attr_accessor` methods? Or `add_*` like `add_include` and `add_extend` (we should probably standardize all methods on one or the other, unless I'm missing some reason to use both `create_` and `add_`).

**Comment by AaronC81** [comment]
Yeah, this is an important feature that will need adding!

I'm not too sure about my choices of naming yet myself. My current system has been:

  - `create` methods take a block which is given the new instance, for things with configurable properties like comments or children. (More formally, everything with `create` returns an `RbiObject`)
  - `add` methods don't take a block, because the things they insert are defined entirely by their constructor, like extends/includes.
